get_train_composition:
  fields:
    departure_date:
      required: true
      example: "2026-09-14"
      selector:
        date:
    train_number:
      required: true
      example: 8
      selector:
        number:
          min: 1
          max: 99999
          mode: box
